language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: GXk1IJ3VJyP2ErvUyVOFDk9/JxyYyrAMi+qoCDO/919mcrNuJjlWhwQP6yjHqwPf64do7ku6NlB4bGtC6shzGYWvJaYRArI1XCVqUkRQN+8uVYafRoURDTs0yKoy/ib/vBxHqPbk7c8J/OlDgKwjOaOn7Xok+s2bIOtznlZj00YuaVGJNt4yeHlgPsHHkBL9WR7CbfeY6SA3BrMuDReS6bhXWkZOpkXfXa2+f5wg5DbubmJQlYOVpkbTOIys2qzhr7RHfjEoucr+imQWe3qD+iNefjrtLdiw5qwAH21Ijhe8HTTtsd4r75K2heTWeNe59hFibncRvlAW2zvO6ELkejDgO1w7EiKOpkfDYzMWUHdrqV3AN5eKgmov49PkqF2n1kbgw2I68skw5xypmr5vSmkfXPnC3QRDFoeiQa2qcE0fKzadZx7117Bs8eTPqHUU4R7V2oqWSKXmPbC+JjlPtdYsUjFNclHr4ih6Ik3ei/i2+9sXKOdZ4gN5CagvBvXureLxpYP4+oJUXOSiOYXmViyh9lBCfQoOa5D5JfFuJXhsUu/saKNPGTJ+CmZGuXXeVyITfv+B7nQtUXW8yNMxvdVJbZnhFNhksa+unLuIm7aBpVtbubLhvcMWfaxHtE0xG0iLQ3s4gaOb67q2rZqn3cknY+26tXIqnahViUSVR18=
  app: crossfitlingo
  on:
    repo: webbkyr/crossfit-terms-server
